# Generated by Django 4.2.1 on 2023-05-05 06:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1000)),
                ('slug', models.SlugField(unique=True)),
                ('copertina', models.ImageField(upload_to='immagini_post/')),
                ('descrizione_alt', models.TextField(default='Nessuna descrizione alt fornita per questa immagine')),
                ('meta_descrizione', models.CharField(max_length=130)),
            ],
        ),
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=2000)),
                ('slug', models.SlugField(unique=True)),
                ('corpo', models.TextField()),
                ('copertina', models.ImageField(upload_to='immagini_post/')),
                ('descrizione_alt', models.TextField(default='Nessuna descrizione alt fornita per questa immagine')),
                ('meta_descrizione', models.CharField(max_length=130)),
                ('data_pubblicazione', models.DateField(default=datetime.date.today)),
                ('autore', models.ForeignKey(default='Nessun autore specificato', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(default='Nessuna categoria', on_delete=django.db.models.deletion.SET_DEFAULT, to='news.categoria')),
            ],
        ),
    ]
