# Generated by Django 4.2.1 on 2023-05-05 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='copertina',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='descrizione_alt',
        ),
    ]
