# Generated by Django 4.2.1 on 2023-05-08 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_articolo_autore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articolo',
            name='autore',
        ),
    ]
