# Generated by Django 4.1.5 on 2023-03-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userArea', '0006_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_viewed_servizi_attivi',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
