# Generated by Django 4.1.5 on 2023-04-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userArea', '0007_customuser_last_viewed_servizi_attivi'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_subscription',
            field=models.BooleanField(default='False'),
        ),
    ]
