# Generated by Django 4.1.5 on 2023-04-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userArea', '0008_customuser_has_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
