# Generated by Django 4.1.5 on 2023-04-03 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userArea', '0009_customuser_stripe_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
