# Generated by Django 4.2.1 on 2023-05-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_servizio_prezzo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servizio',
            name='descrizione_stripe',
            field=models.TextField(default=''),
        ),
    ]
