# Generated by Django 4.2.1 on 2023-05-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_servizioattivato'),
    ]

    operations = [
        migrations.AddField(
            model_name='servizio',
            name='nome_app',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='servizio',
            name='nome_modello_pratica',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
