# Generated by Django 4.2.1 on 2023-05-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_servizio_nome_app_servizio_nome_modello_pratica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servizio',
            name='nome_app',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='servizio',
            name='nome_modello_pratica',
            field=models.CharField(max_length=2000),
        ),
    ]
