# Generated by Django 4.2.1 on 2023-05-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_servizio_nome_app_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servizioattivato',
            name='abbonamento_attivo',
            field=models.BooleanField(default=True),
        ),
    ]
