# Generated by Django 4.2.1 on 2023-05-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_servizioattivato_abbonamento_attivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servizioattivato',
            name='abbonamento_id',
            field=models.TextField(default=''),
        ),
    ]
