# Generated by Django 4.2.1 on 2023-05-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_notifica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1000)),
            ],
        ),
    ]
