# Generated by Django 4.2.1 on 2023-05-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utenti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='immagine_profilo',
            field=models.ImageField(blank=True, upload_to='immagini_utenti/'),
        ),
    ]
