# Generated by Django 4.1.5 on 2023-02-20 16:43

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FontiCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fonti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=3000)),
                ('sotto_titolo', models.CharField(blank=True, max_length=3000)),
                ('slug', models.SlugField(max_length=1000, unique_for_date='publish')),
                ('corpo', models.TextField()),
                ('descrizione', models.TextField(default=models.SlugField(max_length=1000, unique_for_date='publish'))),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('autore', models.ManyToManyField(db_constraint=False, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ManyToManyField(db_constraint=False, to='blog.fonticategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=1000)),
                ('slug', models.SlugField(max_length=1000, unique_for_date='publish')),
                ('copertina', models.ImageField(upload_to='images/blog/')),
                ('corpo', models.TextField()),
                ('descrizione', models.TextField(default=models.SlugField(max_length=1000, unique_for_date='publish'))),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('autore', models.ManyToManyField(db_constraint=False, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ManyToManyField(db_constraint=False, to='blog.categoria')),
            ],
        ),
    ]
