# Generated by Django 4.1.5 on 2023-02-20 16:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='autore',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articolo',
            name='categoria',
            field=models.ManyToManyField(blank=True, null=True, to='blog.categoria'),
        ),
    ]
