# Generated by Django 4.1.5 on 2023-02-20 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_alter_articolo_autore_alter_articolo_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articolo',
            name='autore',
        ),
        migrations.RemoveField(
            model_name='articolo',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='fonti',
            name='autore',
        ),
        migrations.RemoveField(
            model_name='fonti',
            name='categoria',
        ),
        migrations.AddField(
            model_name='articolo',
            name='autore',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articolo',
            name='categoria',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.categoria'),
        ),
        migrations.AddField(
            model_name='fonti',
            name='autore',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fonti',
            name='categoria',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.fonticategoria'),
        ),
    ]
