# Generated by Django 4.1.5 on 2023-04-07 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recuperoCredito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviziorecuperocredito',
            name='comunicazioni_non_lette',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviziorecuperocredito',
            name='current_user',
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviziorecuperocredito',
            name='db_cognome',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='serviziorecuperocredito',
            name='db_comune_di_residenza',
            field=models.CharField(
                blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='serviziorecuperocredito',
            name='db_comune_sede_principale',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='serviziorecuperocredito',
            name='db_data_di_nascita',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='serviziorecuperocredito',
            name='db_denominazione_sociale',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='serviziorecuperocredito',
            name='db_indirizzo_di_residenza',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='serviziorecuperocredito',
            name='db_luogo_di_nascita',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='serviziorecuperocredito',
            name='db_nome',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='serviziorecuperocredito',
            name='db_sede_principale',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='serviziorecuperocredito',
            name='db_tipo',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='serviziorecuperocredito',
            name='df_codice_fiscale',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='serviziorecuperocredito',
            name='df_partita_iva',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='serviziorecuperocredito',
            name='dj_codice_fiscale',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='serviziorecuperocredito',
            name='dj_partita_iva',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='serviziorecuperocredito',
            name='first_payment',
            field=models.DecimalField(
                decimal_places=2, default='0.00', max_digits=12),
        ),
        migrations.AddField(
            model_name='serviziorecuperocredito',
            name='procura_speciale',
            field=models.FileField(
                null=True, upload_to='recupero_credito_doc'),
        ),
        migrations.AddField(
            model_name='serviziorecuperocredito',
            name='somma',
            field=models.DecimalField(
                decimal_places=2, default='0.00', max_digits=12),
        ),
        migrations.AddField(
            model_name='serviziorecuperocredito',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comuni',
            name='nome',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='serviziorecuperocredito',
            name='cr_comune_di_residenza',
            field=models.CharField(
                blank=True, default='', max_length=1000, null=True),
        ),
    ]
