# Generated by Django 4.1.5 on 2023-04-11 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recuperoCredito', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviziorecuperocredito',
            old_name='current_user',
            new_name='current_user_id',
        ),
    ]
