# Generated by Django 4.1.5 on 2023-02-16 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recuperoCredito', '0003_tribunali'),
    ]

    operations = [
        migrations.AddField(
            model_name='comuni',
            name='tribunale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recuperoCredito.tribunali'),
        ),
    ]
