# Generated by Django 4.1.5 on 2023-02-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperoCredito', '0005_serviziorecuperocredito_current_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviziorecuperocredito',
            name='db_tipo',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
