# Generated by Django 4.1.5 on 2023-02-22 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recuperoCredito', '0006_serviziorecuperocredito_db_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comuni',
            name='tribunale',
        ),
    ]
