# Generated by Django 4.1.5 on 2023-02-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperoCredito', '0007_remove_comuni_tribunale'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviziorecuperocredito',
            name='numero_debitori',
            field=models.IntegerField(blank=True, default='1'),
        ),
    ]
