# Generated by Django 4.1.5 on 2023-02-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperoCredito', '0009_serviziorecuperocredito_db_pf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviziorecuperocredito',
            name='somma',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
