# Generated by Django 4.1.5 on 2023-02-22 13:25

from django.db import migrations, models
import recuperoCredito.models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperoCredito', '0012_alter_serviziorecuperocredito_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviziorecuperocredito',
            name='time',
            field=models.DateField(default=recuperoCredito.models.get_current_date),
        ),
    ]
