# Generated by Django 4.1.5 on 2023-02-22 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperoCredito', '0014_alter_serviziorecuperocredito_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviziorecuperocredito',
            name='time',
            field=models.DateField(default=datetime.date(2023, 2, 22), editable=False),
        ),
    ]
