# Generated by Django 4.1.5 on 2023-02-22 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recuperoCredito', '0016_alter_serviziorecuperocredito_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviziorecuperocredito',
            name='time',
        ),
    ]
