# Generated by Django 4.1.5 on 2023-02-23 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recuperoCredito', '0024_alter_serviziorecuperocredito_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviziorecuperocredito',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
