# Generated by Django 4.1.5 on 2023-03-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperoCredito', '0027_serviziorecuperocredito_somma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviziorecuperocredito',
            name='somma',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=12),
        ),
    ]
