# Generated by Django 4.1.5 on 2023-03-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperoCredito', '0028_alter_serviziorecuperocredito_somma'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviziorecuperocredito',
            name='messaggi',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
