# Generated by Django 4.1.5 on 2023-03-18 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recuperoCredito', '0029_serviziorecuperocredito_messaggi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviziorecuperocredito',
            name='messaggi',
        ),
        migrations.CreateModel(
            name='MessaggioRecuperoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.CharField(blank=True, max_length=10000)),
                ('pratica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recuperoCredito.serviziorecuperocredito')),
            ],
        ),
    ]
