# Generated by Django 4.1.5 on 2023-03-18 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recuperoCredito', '0030_remove_serviziorecuperocredito_messaggi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messaggiorecuperocredito',
            name='pratica',
        ),
        migrations.AddField(
            model_name='serviziorecuperocredito',
            name='comunicazioni',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='recuperoCredito.messaggiorecuperocredito'),
        ),
    ]
