# Generated by Django 4.1.5 on 2023-03-18 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recuperoCredito', '0031_remove_messaggiorecuperocredito_pratica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviziorecuperocredito',
            name='comunicazioni',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='recuperoCredito.messaggiorecuperocredito'),
        ),
    ]
