# Generated by Django 4.1.5 on 2023-03-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperoCredito', '0032_alter_serviziorecuperocredito_comunicazioni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviziorecuperocredito',
            name='comunicazioni',
        ),
        migrations.AddField(
            model_name='serviziorecuperocredito',
            name='comunicazioni',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='recuperoCredito.messaggiorecuperocredito'),
        ),
    ]
