# Generated by Django 4.1.5 on 2023-03-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperoCredito', '0033_remove_serviziorecuperocredito_comunicazioni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviziorecuperocredito',
            name='comunicazioni',
            field=models.ManyToManyField(blank=True, default=None, to='recuperoCredito.messaggiorecuperocredito'),
        ),
    ]
