# Generated by Django 4.1.5 on 2023-03-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperoCredito', '0034_alter_serviziorecuperocredito_comunicazioni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messaggiorecuperocredito',
            name='testo',
            field=models.TextField(),
        ),
    ]
