# Generated by Django 4.1.5 on 2023-03-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperoCredito', '0036_remove_serviziorecuperocredito_comunicazioni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviziorecuperocredito',
            name='comunicazioni_non_lette',
            field=models.IntegerField(default=0),
        ),
    ]
