# Generated by Django 4.1.5 on 2023-03-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperoCredito', '0037_serviziorecuperocredito_comunicazioni_non_lette'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviziorecuperocredito',
            name='comunicazioni_precedenti',
            field=models.TextField(default=''),
        ),
    ]
