# Generated by Django 4.1.5 on 2023-03-19 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recuperoCredito', '0038_serviziorecuperocredito_comunicazioni_precedenti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviziorecuperocredito',
            name='comunicazioni_precedenti',
        ),
    ]
