# Generated by Django 4.1.5 on 2023-03-20 07:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recuperoCredito', '0039_remove_serviziorecuperocredito_comunicazioni_precedenti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviziorecuperocredito',
            name='comunicazioni',
        ),
        migrations.AddField(
            model_name='messaggiorecuperocredito',
            name='data_creazione',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='messaggiorecuperocredito',
            name='servizio_recupero_credito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recuperoCredito.serviziorecuperocredito'),
        ),
    ]
