# Generated by Django 4.1.5 on 2023-03-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperoCredito', '0040_remove_serviziorecuperocredito_comunicazioni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messaggiorecuperocredito',
            name='letta',
            field=models.BooleanField(default=False),
        ),
    ]
