# Generated by Django 4.2.1 on 2023-05-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recupero_credito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='praticarecuperocredito',
            name='compilazione_terminata',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='praticarecuperocredito',
            name='cr_data_di_nascita',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='praticarecuperocredito',
            name='db_data_di_nascita',
            field=models.DateField(blank=True, null=True),
        ),
    ]
