# Generated by Django 4.2.1 on 2023-05-13 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recupero_credito', '0002_praticarecuperocredito_compilazione_terminata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenuto', models.TextField()),
                ('letta', models.BooleanField(default=False)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('pratica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recupero_credito.praticarecuperocredito')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utente_recupero_credito', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
