# Generated by Django 4.2.1 on 2023-05-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recupero_credito', '0003_notifica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praticarecuperocredito',
            name='cr_data_di_nascita',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='praticarecuperocredito',
            name='db_data_di_nascita',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
