# Generated by Django 4.2.1 on 2023-05-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recupero_credito', '0004_alter_praticarecuperocredito_cr_data_di_nascita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praticarecuperocredito',
            name='cr_data_di_nascita',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='praticarecuperocredito',
            name='db_data_di_nascita',
            field=models.DateField(blank=True, null=True),
        ),
    ]
