# Generated by Django 4.2.1 on 2023-05-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recupero_credito', '0005_alter_praticarecuperocredito_cr_data_di_nascita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='praticarecuperocredito',
            name='frima_digitale',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=1000),
        ),
    ]
