# Generated by Django 4.2.1 on 2023-05-15 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recupero_credito', '0006_praticarecuperocredito_frima_digitale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='praticarecuperocredito',
            old_name='frima_digitale',
            new_name='firma_digitale',
        ),
    ]
