# Generated by Django 4.2.1 on 2023-05-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recupero_credito', '0007_rename_frima_digitale_praticarecuperocredito_firma_digitale'),
    ]

    operations = [
        migrations.AddField(
            model_name='praticarecuperocredito',
            name='carta_identita_fronte',
            field=models.FileField(blank=True, upload_to='documenti_identita'),
        ),
        migrations.AddField(
            model_name='praticarecuperocredito',
            name='carta_identita_retro',
            field=models.FileField(blank=True, upload_to='documenti_identita'),
        ),
    ]
