# Generated by Django 4.2.1 on 2023-05-15 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recupero_credito', '0009_praticarecuperocredito_totale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='praticarecuperocredito',
            old_name='totale',
            new_name='prezzo',
        ),
    ]
