# Generated by Django 4.2.1 on 2023-05-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recupero_credito', '0010_rename_totale_praticarecuperocredito_prezzo'),
    ]

    operations = [
        migrations.AddField(
            model_name='praticarecuperocredito',
            name='pagamento_iniziale',
            field=models.BooleanField(default=False),
        ),
    ]
